server:
  port: 7005

spring:
  application:
    name: client-zuul

eureka:
  client:
    service-url:
     defaultZone: http://user:123456@localhost:7001/eureka/
zuul:
  #ignoredPatterns: /order/orderDetail
  routes:
     #client-order: /order/** #/orderDetail -> /order/orderDetail
    orderaaa:
      path: /order/**
      serviceId: client-order
management:
  security:
    enabled: false
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #断路器超时时间，默认1000ms
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000



