server:
  port: 7002
spring:
  application:
    name: client-order
eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:7001/eureka/
feign:
  hystrix:
    enabled: true
client-goods:
  ribbon:
    NFLoadBalancerRulerClassName: com.netflix.loadbalancer.RandomRule